version: '2.4'

x-database-variables: &database-variables
  SPRING_DATASOURCE_URL: jdbc:mysql://database_mysql:3306/bank_transactions?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&sslMode=DISABLED
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: root

services:

  db:
    image: mysql
    container_name: database_mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - bank_transactions:/var/lib/mysql
    mem_limit: 512m

  bank-transactions:
    container_name: bank-transactions
    image: harissonnascimento/bank-transactions
    ports:
    - "8080:8080"
    mem_limit: 512m
    depends_on:
      - db
    environment:
      <<: *database-variables


volumes:
  bank_transactions: