server:
  port: 8080

spring:
  application:
    name: bank-transactions
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/bank_transactions?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: root

jwt:
  config:
    type: signed
    login-url: /login

info:
  app: Bank Transactions
  github: https://github.com/HarissonNascimento
  developer: Harisson Nascimento
  linkedin: https://www.linkedin.com/in/harisson-nascimento/
